### ISSUE TITLE
Improve UX of existing Skills contribution form

### ISSUE THREAD

**Issue by Misjohns** [instructlab/ui#107] opened 2024-08-02 20:19 UTC
The current InstructLab Contribute Skill workflow is not intuitive and does not provide enough guidance to the user.

@beaumorley

**Comment by Misjohns** [comment] 2024-08-02 20:21
UX is capturing the current flow and making initial comments in a miro board:
[InstructLab Contribute Skill Flow evaluation](https://miro.com/app/board/uXjVKtWsH_g=/?share_link_id=638054834509)

**Comment by vishnoianil** [comment] 2024-09-14 06:52
@Misjohns Most of the suggestion you provides in the Miro boards is implemented. Such as 

- Addition of page title and description
- All the required fields are marked now, and it throws error if the field is not populated.
- File path now shows a tree of taxonomy directory that user can use to choose the target directory. Further improvements to this feature is tracked through #147 
- Submit button is disabled till user fill all the required field and validated.
- Download button is added to download the yaml and attribution file. Download button would be disabled till user fill all the required fields.
- View button is added to show the yaml and attribution file.

Two of the other proposed enhancement are not yet done and I opened following issues to track those #171 and #172 specifically.

**Comment by vishnoianil** [comment] 2024-09-14 06:57
@Misjohns I am closing this issue, because the major changes in skill forms are implemented.
In general it improves the chances of contributors picking up issue if the issue is clearly scoped for specific enhancement, so I opened separate issues for those remaining improvements. If i missed any enhancement, please feel free to open an issue to track that. Thanks

**Closed by vishnoianil** 2024-09-14 06:57 UTC
Labels: UX
